//>>built
function includedctermsnamespace(a){setTimeout(function(){if(2>a.split("rdf:about").length-1&&1>a.split('xmlns:dcterms\x3d"http://purl.org/dc/terms/"').length-1){dcterms="http://purl.org/dc/terms/";var b=dijit.byId("dijit_form_SimpleTextarea_1").get("value");posStartTag=b.indexOf("\x3crdf:RDF ");b=b.substr(0,posStartTag+9)+'xmlns:dcterms\x3d"http://purl.org/dc/terms/"\n    '+b.substr(posStartTag+9);dijit.byId("dijit_form_SimpleTextarea_1").set("value",b)}},10)}
function convertToCPSV(){setTimeout(function(){var a=dijit.byId("dijit_form_SimpleTextarea_1");includedctermsnamespace(a.get("value"));a.set("value",transformRDFXMLtoCPSV(a.get("value")))},10)}function convertToEditor(){var a=dijit.byId("dijit_form_SimpleTextarea_1");a.set("value",transformRDFXMLtoEditor(a.get("value")))}
function transformRDFXMLtoCPSV(a){var b,c,d=-1;b=a.indexOf('\x3crdf:Description rdf:about\x3d"http://www.w3.org/ns/dcat#"\x3e');c=a.indexOf("\x3cdcat:identifier",b);d=a.indexOf("\x3c/rdf:Description\x3e",b);if(-1!=b&&-1!=c&&-1!=d&&b<c&&c<d)c=a.indexOf("\x3e",c)+1,d=a.indexOf("\x3c",c),c=a.substring(c,d),a=a.substr(0,d+21)+'\n    \x3crdf:type rdf:resource\x3d"http://purl.org/vocab/cpsv#PublicService"/\x3e'+a.substr(d+21),a=isURL(c)?a.replace("http://www.w3.org/ns/dcat#",c):a.replace('rdf:about\x3d"http://www.w3.org/ns/dcat#',
'rdf:nodeID\x3d"'+c);else if(-1==c&&-1!=b&&-1!=d||-1!=b&&-1!=c&&-1!=d)a=a.replace('rdf:about\x3d"http://www.w3.org/ns/dcat#','rdf:nodeID\x3d"PS_0'),index=a.indexOf('rdf:nodeID\x3d"PS_0"\x3e'),a=a.substr(0,index+18)+'\n    \x3crdf:type rdf:resource\x3d"http://purl.org/vocab/cpsv#PublicService"/\x3e\n    \x3cdcat:identifier\x3ePS_0\x3c/dcat:identifier\x3e'+a.substr(index+18);d=a.indexOf("\x3c/rdf:Description\x3e",b);b=-1;for(var e=null;-1!=a.indexOf("\x3cdcat:identifier",d);)if(b=a.indexOf("dcat:identifier",
d),c=a.indexOf("\x3e",b)+1,d=a.indexOf("\x3c",c),c=a.substring(c,d),d=a.lastIndexOf("nodeID",b)+8,b=a.indexOf('"',d),e=a.substring(d,b),d=a.indexOf("\x3c/rdf:Description\x3e",b),isURL(c))for(a=a.replace('rdf:Description rdf:nodeID\x3d"'+e,'rdf:Description rdf:about\x3d"'+c);-1!=a.indexOf(e);)a=a.replace('rdf:nodeID\x3d"'+e,'rdf:resource\x3d"'+c);else for(;-1!=a.indexOf(e);)a=a.replace('rdf:nodeID\x3d"'+e,'rdf:nodeID\x3d"'+c);return a}
function transformRDFXMLtoEditor(a){var b=a.indexOf('\x3crdf:type rdf:resource\x3d"http://purl.org/vocab/cpsv#PublicService"/\x3e'),c=a.lastIndexOf("\x3crdf:Description",b),d=a.indexOf("rdf:about\x3d"),e=a.indexOf("rdf:nodeID\x3d");if(-1!=b&&-1!=c&&-1!=d&&c<d&&d<b){var b=a.indexOf('"',d)+1,f=a.indexOf('"',b),c=a.substring(b,f);a=a.replace(c,"http://www.w3.org/ns/dcat#");a=a.replace('\x3crdf:type rdf:resource\x3d"http://purl.org/vocab/cpsv#PublicService"/\x3e',"");a=a.replace(/^\s*[\r\n]/gm,"")}else-1!=
b&&(-1!=c&&-1!=e&&c<e&&e<b)&&(b=a.indexOf('"',e)+1,f=a.indexOf('"',b),c=a.substring(b,f),a=a.replace('rdf:nodeID\x3d"'+c,'rdf:about\x3d"http://www.w3.org/ns/dcat#'),a=a.replace('\x3crdf:type rdf:resource\x3d"http://purl.org/vocab/cpsv#PublicService"/\x3e',""),a=a.replace(/^\s*[\r\n]/gm,""));for(b=b=-1;-1!=a.indexOf("rdf:about",f);){f=a.indexOf("rdf:about",f);c=a.indexOf('"',f)+1;f=a.indexOf('"',c);c=a.substring(c,f);b+=1;for(a=a.replace('rdf:about\x3d"'+c,'rdf:nodeID\x3d"_n'+b);-1!=a.indexOf('rdf:resource\x3d"'+
c);)a=a.replace('rdf:resource\x3d"'+c,'rdf:nodeID\x3d"_n'+b)}return a}function isURL(a){return RegExp("^(https?:\\/\\/)?((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|((\\d{1,3}\\.){3}\\d{1,3}))(\\:\\d+)?(\\/[-a-z\\d%@_.~+\x26:]*)*(\\?[;\x26a-z\\d%@_.,~+\x26:\x3d-]*)?(\\#[-a-z\\d_]*)?$","i").test(a)};
//# sourceMappingURL=convert.js.map