//>>built
define("rdforms/view/Editor","dojo/_base/declare dojo/_base/lang dojo/aspect dojo/on dojo/dom-class dojo/dom-construct dojo/dom-attr dojo/_base/array ../utils ./Presenter ./TreeOntologyChooser dojo/store/Memory ./DateTime ./Duration ../model/system ../template/Group ../template/PropertyGroup ../template/Choice ../model/Engine dijit/TitlePane dijit/form/TextBox dijit/form/ValidationTextBox dijit/form/Textarea dijit/form/FilteringSelect dijit/form/RadioButton".split(" "),function(J,n,x,q,l,g,y,w,z,
K,L,M,N,O,E,A,P,Q,p,R,F,B,S,G,T){var H=0,I=function(b,a,e){if(b.hasStyle("invisible"))return!1;if(0<a.length)if(!b.getProperty()&&b instanceof A){var f=b.getChildren(),c=a[0].getItemGroupedChildBindings(),d;for(d=0;d<c.length;d++)if(a=c[d],b=f[d],I(b,a,e))return!0}else return!0;b=b.getCardinality();switch(e){case "mandatory":return b&&1<=b.min;case "recommended":return b&&(1<=b.min||1<=b.pref);default:return!0}},C=J(K,{filterTranslations:!1,styleCls:"rformsEditor",ontologyPopupWidget:null,includeLevel:"recommended",
report:function(b){b||(b=this.binding.report());for(var a in this._binding2node)l.remove(this._binding2node[a],"errorReport");for(a=0;a<b.errors.length;a++)if(b.errors[a].parentBinding===this.binding)for(var e=b.errors[a].item,f=this.binding.getChildBindingsFor(e),e=e.getCardinality().min,c=0;c<f.length&&0<e;c++)e--,f[c].isValid()||l.add(this._binding2node[f[c].getHash()],"errorReport");for(a=0;a<this._subEditors.length;a++)this._subEditors[a].report(b)},buildRendering:function(){this._subEditors=
[];this.inherited("buildRendering",arguments)},show:function(b){this._subEditors=[];this.inherited("show",arguments)},showNow:function(b,a){return I(b,a,this.includeLevel)},prepareBindings:function(b,a){var e=b.getCardinality(),e=0<e.pref?e.pref:0<e.min?e.min:b instanceof P?0:b instanceof A?null==b.getProperty()?1:0:1;if(e>a.length)for(a=a.concat([]);e>a.length;)a.push(p.create(this.binding,b));return a},skipBinding:function(b){return!1},addLabel:function(b,a,e,f){if(f.hasStyle("nonEditable"))return l.add(a,
"rformsLabelRow"),this.inherited("addLabel",arguments);var c=f instanceof A,d=f.getLabel(),d=null!=d&&""!=d?d.charAt(0).toUpperCase()+d.slice(1):"",d=g.create("span",{innerHTML:d},a);l.add(a,"rformsLabelRow");l.add(d,"rformsLabel");this.showInfo(f,d);null==e?this._addExpandButton(b,a,f):this.showAsTable(f)||(d=f.getCardinality(),null!=d.max&&(d.max==d.min||1===d.max)||(c?this._addGroupButtons(b,a,e):this._addCreateChildButton(b,a,e)))},addGroup:function(b,a){if(a.getItem().hasStyle("nonEditable"))return this.inherited("addGroup",
arguments);var e;if(a.getItem().hasStyle("expandable")){e=new R({open:!1},b);var f=g.create("div");e.set("content",f);e=new C({languages:this.languages,binding:a,topLevel:!1,includeLevel:this.includeLevel},f)}else e=new C({languages:this.languages,binding:a,topLevel:!1,includeLevel:this.includeLevel},b);this._subEditors.push(e)},addText:function(b,a,e){if(a.getItem().hasStyle("nonEditable"))return this.inherited("addText",arguments);var f=g.create("div",{"class":"rformsFieldControl"},b),c=a.getItem(),
d=c.getNodetype(),h=c.getDatatype(),k;"DATATYPE_LITERAL"==d||h?"http://www.w3.org/2001/XMLSchema#date"===h||"http://purl.org/dc/terms/W3CDTF"===h?k=new N({binding:a,item:c},g.create("div",null,b)):"http://www.w3.org/2001/XMLSchema#duration"===h?k=new O({disabled:!c.isEnabled(),binding:a},g.create("div",null,b)):"http://www.w3.org/2001/XMLSchema#integer"===h?k=new B({value:a.getValue(),disabled:!c.isEnabled(),invalidMessage:"Only an integer value is allowed, value will not be saved",regExp:"[0-9]*",
onChange:function(){k.isValid()?a.setValue(this.get("value")):a.setValue("")}},g.create("div",null,b)):"http://www.w3.org/2001/XMLSchema#decimal"===h?k=new B({value:a.getValue(),disabled:!c.isEnabled(),invalidMessage:"Only a decimal value is allowed, value will not be saved",regExp:"[0-9]*.?[0-9]*",onChange:function(){k.isValid()?a.setValue(this.get("value")):a.setValue("")}},g.create("div",null,b)):(k=new F({value:a.getValue(),onChange:function(){a.setValue(this.get("value"))}},g.create("div",null,
b)),l.add(k.domNode,"rformsFieldInput")):(c=a.getItem(),"ONLY_LITERAL"===c.getNodetype()&&null!=c.getPattern()?k=new B({value:a.getValue(),pattern:c.getPattern(),invalidMessage:c.getDescription(),onChange:function(){a.setValue(this.get("value"))}},g.create("div",null,b)):c.hasStyle("multiline")?(k=new S({value:a.getValue(),onChange:function(){a.setValue(this.get("value"))}},g.create("div",null,b)),k.resize()):k=new F({value:a.getValue(),onChange:function(){a.setValue(this.get("value"))}},g.create("div",
null,b)),l.add(k.domNode,"rformsFieldInput"));if("LANGUAGE_LITERAL"===d||"PLAIN_LITERAL"===d){var c=g.create("span",null,f),h=this._getLanguagesList(),h=this._getStoreFromArray(h,a.getItem(),!0),m=new G({store:h,searchAttr:"label"},c);m.set("value",a.getLanguage()||"");q(m,"change",n.hitch(this,function(){a.setLanguage(m.getValue())}));l.add(c,"rformsLanguage");l.add(b,"rformsLangcontrolledfield");l.add(f,"rformsLangFieldControl")}!0!==e&&this._addRemoveButton(b,a,f,function(){k.set("value","");("LANGUAGE_LITERAL"===
d||"PLAIN_LITERAL"===d)&&m.set("value","")})},addChoice:function(b,a,e){if(a.getItem().hasStyle("nonEditable"))return this.inherited("addChoice",arguments);var f=g.create("div",{"class":"rformsFieldControl"},b),c=a.getItem();if(c.hasChoices()){var d=c.getChoices(),h=g.create("div",null,b),k=c.getHierarchyProperty()||c.hasStyle("tree");if(!k&&!c.hasStyle("dropDown")&&(5>d.length||c.hasStyle("verticalRadioButtons")||c.hasStyle("horizontalRadioButtons"))&&1===c.getCardinality().max){null!=a.getChoice()&&
a.getChoice().mismatch&&(d=d.slice(0),d.push(a.getChoice()));for(var m=[],k=0;k<d.length;k++){var t=d[k],r=g.create("input",null,h),p=g.create("span",{"class":"rformsChoiceLabel",innerHTML:c._getLocalizedValue(t.label).value},h);c.hasStyle("verticalRadioButtons")&&g.create("br",null,h);r=new T({name:"RadioButtonName"+H,value:t.value,checked:t.value===a.getValue()},r);t.mismatch?(l.add(p,"mismatch"),r.set("disabled",!0)):q(r,"change",n.hitch(this,function(b){b=b.get("value");!1!==b&&a.setValue(b)},
r));m.push(r)}H++;!0!==e&&this._addRemoveButton(b,a,f,function(){w.forEach(m,function(a){a.set("value",!1)})})}else{var s,c=this._createChoiceStore(c),d=g.create("span",null,h);s=new G({store:c,query:{selectable:!0},searchAttr:"label"},d);a.getValue()?a.getChoice().mismatch?s.set("displayedValue",a.getValue()):s.set("value",a.getValue()):s.set("value","");s.onChange=n.hitch(this,function(b){a.setValue(b)});if(k){var D,h=g.create("span",{"class":"action editSearch",title:"Browse"},h);q(h,"click",n.hitch(this,
function(){null==D&&(D=new L({binding:a,done:n.hitch(this,function(){s.set("value",a.getValue())})}));D.show()}))}!0!==e&&this._addRemoveButton(b,a,f,function(){s&&s.set("value","")})}}else if(null!=E.getChoice){var h=g.create("div",null,b),u=g.create("div",{"class":"rformsChoiceValue"},h),v=a.getChoice();null!=v&&v.mismatch&&l.add(u,"mismatch");v&&(y.set(u,"innerHTML",z.getLocalizedValue(v.label).value||""),null!=v.load&&v.load(function(){y.set(u,"innerHTML",z.getLocalizedValue(v.label).value||"")}));
h=g.create("span",{"class":"action editSearch",title:"Browse"},h);q(h,"click",n.hitch(this,function(){E.openChoiceSelector(a,function(b){a.setChoice(b);b&&(y.set(u,"innerHTML",z.getLocalizedValue(b.label).value||"\x26nbsp;"),l.remove(u,"mismatch"))})}));!0!==e&&this._addRemoveButton(b,a,f,function(){a.setValue("");u&&y.set(u,"innerHTML","")})}},addTable:function(b,a){if(a.getItem().hasStyle("nonEditable"))return this.inherited("addGroup",arguments);var e=a.getItem(),f=e.getChildren(),c=g.create("table",
null,b);l.add(c,"rformsGroup");tHead=g.create("thead",null,c);tHeadRow=g.create("tr",null,c);for(colInd=0;colInd<f.length;colInd++){var d=g.create("th",null,tHeadRow);l.add(d,"rformsColumnHeader"+colInd);this.showInfo(e,g.create("span",{innerHTML:f[colInd].getLabel()},d))}if(!a.getItem().hasStyle("firstcolumnfixedtable")){var f=g.create("th",{"class":"rformsTableControl"},tHeadRow),h=a.getParent(),k=g.create("span",{"class":"action editAdd",title:"Add"},f),m=a.getCardinalityTracker();q(k,"click",
n.hitch(this,function(){if(!m.isMax()){var a=p.create(h,e);this._addTableRow(c,a)}}));x.after(m,"cardinalityChanged",function(){l.toggle(k,"disabled",m.isMax())})}return c},fillTable:function(b,a){if(0!==a.length){var e=a[0].getItem();if(e.hasStyle("nonEditable"))return this.inherited("addGroup",arguments);e.hasStyle("firstcolumnfixedtable")&&(a=this._createChildBindingsForFirstFixedColumn(a));w.forEach(a,n.hitch(this,this._addTableRow,b))}},_createChildBindingsForFirstFixedColumn:function(b){var a=
[],e=b[0].getItem(),f=e.getChildren()[0],c=f.getChoices(),c=this._getCopiedLabeledChoices(c,e);c.sort(function(a,b){return a.label>b.label?1:a.label<b.label?-1:0});var d={};w.forEach(b,function(a){var b=a.getItemGroupedChildBindings();0<b.length&&0<b[0].length&&(d[b[0][0].getValue()]=a)});var g=b[0].getParent();w.forEach(c,function(b){if(null!=d[b.value])a.push(d[b.value]);else{var c=p.create(g,e),l=p.create(c,f);l.setExcludeFromTreeValidityCheck(!0);l.setAncestorValid(!1);l.setChoice(b);a.push(c)}});
return a},_addCreateChildButton:function(b,a,e){var f=e.getParent(),c=e.getItem(),d=e.getCardinalityTracker(),h=g.create("span",{"class":"action editAdd",title:"add"},a);q(h,"click",n.hitch(this,function(){if(!d.isMax()){var a=p.create(f,c);this.addRow(b,a)}}));x.after(d,"cardinalityChanged",function(){l.toggle(h,"disabled",d.isMax())})},_addGroupButtons:function(b,a,e){var f=e.getParent(),c=e.getItem(),d=g.create("span",{"class":"action editAdd",title:"add"},a),h=g.create("span",{"class":"action editDelete",
title:"remove"},a),k=e.getCardinalityTracker(),m=x.after(k,"cardinalityChanged",function(){l.toggle(d,"disabled",k.isMax());l.toggle(h,"disabled",k.isMin())}),t=q(d,"click",n.hitch(this,function(){if(!k.isMax()){var a=p.create(f,c);this.addRow(b,a)}})),r=q(h,"click",n.hitch(this,function(){if(!k.isMin()){if(1===k.getCardinality()){var a=e.getParent(),c=e.getItem();m.remove();t.remove();r.remove();e.remove();var d=c.getCardinality();0<d.pref||0<d.min?(a=p.create(a,c),this.addRow(b,a)):this.addLabelClean(b,
null,c)}else m.remove(),t.remove(),r.remove(),e.remove();g.destroy(b)}}))},_addRemoveButton:function(b,a,e,f){var c=g.create("span",{"class":"action editDelete",title:"remove"},e),d=a.getCardinalityTracker(),h=x.after(d,"cardinalityChanged",function(){l.toggle(c,"disabled",d.isMin())}),k=q(c,"click",function(){d.isMin()||(1===d.getCardinality()?(a.getItem()instanceof Q?a.setChoice(null):a.setValue(null),f()):(h.remove(),k.remove(),a.remove(),g.destroy(b)))})},_addExpandButton:function(b,a,e){var f=
g.create("span",{"class":"action editExpand",title:"Expand"},a),c=q(f,"click",n.hitch(this,function(){var d=p.create(this.binding,e);if(this.showAsTable(e)){var h=this.addTable(b,d,e);this.fillTable(h,[d])}else this.addRow(b,d,!1),this._addGroupButtons(b,a,d);g.destroy(f);c.remove()}))},_addTableRow:function(b,a){var e=a.getItem().getChildren(),f=a.getItemGroupedChildBindings(),c=g.create("tr",null,b);w.forEach(f,function(b,c){0===b.length&&!e[c].hasStyle("nonEditable")&&p.create(a,e[c])});w.forEach(f,
function(a,b){this.addComponent(g.create("td",null,c),a[0],!0)},this);if(!a.getItem().hasStyle("firstcolumnfixedtable"))var f=g.create("td",{"class":"rformsTableControl"},c),d=g.create("span",{"class":"action editDelete",title:"Remove"},f),h=a.getCardinalityTracker(),k=x.after(h,"cardinalityChanged",function(){l.toggle(d,"disabled",h.isMin())}),m=q(d,"click",n.hitch(this,function(){if(!h.isMin()){if(1===h.getCardinality()){var d=a.getParent(),e=a.getItem(),d=p.create(d,e);this._addTableRow(b,d)}k.remove();
m.remove();a.remove();g.destroy(c)}}))},_getLabelForChoice:function(b){if(b=b.getChoice())return z.getLocalizedValue(b.label).value},_createChoiceStore:function(b){return this._getStoreFromArray(b.getChoices(),b)},_getStoreFromArray:function(b,a,e){b=this._getCopiedLabeledChoices(b,a);!0!==e&&!(0<a.getCardinality().min)&&b.push({value:"",label:"",top:!0});return new M({data:b,idProperty:"value",fetchProperties:{sort:[{attribute:"label",descending:!0}]}})},_getCopiedLabeledChoices:function(b,a){for(var e=
[],f=0;f<b.length;f++){var c=b[f],d=a._getLocalizedValue(c.label),d={value:c.value,label:d.value||c.value||""};!0===c.top&&(d.top=!0);null!=c.children&&(d.children=n.clone(c.children));d.selectable=!1===c.selectable?!1:!0;e.push(d)}return e},_getLanguagesList:function(){null==this.languages&&(this.languages=[{value:"",label:{en:""}},{value:"bg",label:{en:"Bulgarian"}},{value:"hr",label:{en:"Croatian"}},{value:"cs",label:{en:"Czech"}},{value:"da",label:{en:"Danish"}},{value:"nl",label:{en:"Dutch"}},
{value:"en",label:{en:"English"}},{value:"et",label:{en:"Estonian"}},{value:"fi",label:{en:"Finnish"}},{value:"fr",label:{en:"French"}},{value:"de",label:{en:"German"}},{value:"el",label:{en:"Greek"}},{value:"hu",label:{en:"Hungarian"}},{value:"ga",label:{en:"Irish"}},{value:"it",label:{en:"Italian"}},{value:"lv",label:{en:"Latvian"}},{value:"lt",label:{en:"Lithuanian"}},{value:"mt",label:{en:"Maltese"}},{value:"pl",label:{en:"Polish"}},{value:"pt",label:{en:"Portuguese"}},{value:"ro",label:{en:"Romanian"}},
{value:"sk",label:{en:"Slovak"}},{value:"sl",label:{en:"Slovenian"}},{value:"es",label:{en:"Spanish"}},{value:"sv",label:{en:"Swedish"}}]);return this.languages}});return C});
//# sourceMappingURL=Editor.js.map