//>>built
define("rdforms/view/View","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-attr dojo/query dijit/_Widget dijit/focus dijit/TooltipDialog dijit/popup ../model/Engine ../model/ValueBinding ../model/GroupBinding ../model/ChoiceBinding ../model/PropertyChoiceBinding ../template/Group".split(" "),function(q,m,e,f,r,s,t,u,v,n,w,x,l,y,z,p){var k;return q(t,{binding:null,template:null,graph:null,resource:"",topLevel:!0,compact:!1,styleCls:"",showNow:function(a,b){},prepareBindings:function(a,
b){},addTable:function(a,b){},fillTable:function(a,b){},addLabel:function(a,b,c){},addGroup:function(a,b){},addText:function(a,b){},addChoice:function(a,b){},showInfo:function(a,b){null==a||null==a.getProperty()&&null==a.getDescription()||(this.connect(b,"onclick",m.hitch(this,this._showInfo,a,b)),e.add(b,"rformsHasInfo"))},constructor:function(a){this._handleParams(a)},_handleParams:function(a){a.binding?this.binding=a.binding:(this.template=a.template||this.template,this.graph=a.graph||this.graph,
this.resource=a.resource||this.resource,null==this.graph||(null==this.resource||null==this.template)||(this.binding=w.match(this.graph,this.resource,this.template)))},buildRendering:function(){this.domNode=this.srcNodeRef;e.add(this.domNode,"rforms");e.add(this.domNode,this.styleCls);this.render()},show:function(a){this._handleParams(a);this.render()},render:function(){r.set(this.domNode,"innerHTML","");if(null!=this.binding){var a,b,c,h=this.binding.getItem().getChildren(),g=this.binding.getItemGroupedChildBindings(),
d;this._binding2node={};(this.compact||this.binding.getItem().hasStyle("compact"))&&!this.binding.getItem().hasStyle("nonCompact")?e.add(this.domNode,"compact"):e.remove(this.domNode,"compact");for(a=0;a<g.length;a++)if(d=g[a],b=h[a],this.showNow(b,d)){d=this.prepareBindings(b,d);if(this.showAsTable(b))c=this.addLabelClean(c,d[0],b),0<d.length&&(b=this.addTable(c,d[0],b),this.fillTable(b,d));else if(0<d.length)for(b=0;b<d.length;b++)c=this.addRow(c,d[b],0===b||d[b]instanceof l);else c=this.addLabelClean(c,
null,b);0<d.length&&d[0].getCardinalityTracker().checkCardinality()}}},addRow:function(a,b,c){var h,e=b.getItem();if(!this.skipBinding(b))return null==c&&(c=b instanceof l),!0===c?(h=this.addLabelClean(a,b,e),c=f.create("div",null,f.create("div",{"class":"rformsFields"},h))):(c=s(".rformsFields",a)[0],c=null!=c?f.create("div",{"class":"rformsRepeatedValue"},c):f.create("div",null,f.create("div",{"class":"rformsFields"},a))),this._binding2node[b.getHash()]=c,this.addComponent(c,b),h||a},skipBinding:function(a){return!1},
addLabelClean:function(a,b,c){a=void 0===a?f.create("div",null,this.domNode):f.create("div",null,a,"after");this.topLevel&&e.add(a,"rformsTopLevel");e.add(a,"rformsRow");c.hasStyle("invisibleGroup")&&e.add(a,"rformsInvisibleGroup");for(var h=c.getClasses(),g=0;g<h.length;g++)-1==h[g].indexOf("rforms")&&e.add(a,h[g]);c instanceof p&&e.add(a,"notCompact");this.addLabel(a,f.create("div",null,a),b,c);return a},addComponent:function(a,b,c){b instanceof l?(e.add(a,"rformsGroup"),this.addGroup(a,b,c)):b instanceof
y||b instanceof z?(e.add(a,"rformsField"),this.addChoice(a,b,c)):b instanceof x&&(e.add(a,"rformsField"),this.addText(a,b,c))},showAsTable:function(a){return a instanceof p&&(a.hasStyle("table")||a.hasClass("rformsTable"))},_showInfo:function(a,b){if(k!==b){k=b;var c=new v({});c.onBlur=function(){n.close(c)};c.openPopup=function(){n.open({popup:c,around:b,onClose:m.hitch(null,function(){c.destroy();setTimeout(function(){b===k&&(k=null)},500)})})};var e=a.getProperty(),g=a.getDescription(),d="\x3cdiv class\x3d'rforms itemInfo'\x3e\x3cdiv class\x3d'itemInfoTable'\x3e",
f=a.getLabel()||"";""!==f&&(d+="\x3cdiv\x3e\x3clabel class\x3d'propertyLabel'\x3eLabel:\x26nbsp;\x3c/label\x3e\x3cspan class\x3d'propertyValue'\x3e"+f+"\x3c/span\x3e\x3c/div\x3e");null!=e&&(e=a.getProperty(),d+="\x3cdiv\x3e\x3clabel class\x3d'propertyLabel'\x3eProperty:\x26nbsp;\x3c/label\x3e\x3ca class\x3d'propertyValue' target\x3d'_blank' href\x3d'"+e+"'\x3e"+e+"\x3c/a\x3e\x3c/div\x3e");null!=g&&(d+="\x3cdiv\x3e\x3clabel class\x3d'descriptionLabel'\x3eDescription:\x26nbsp;\x3c/label\x3e\x3cspan class\x3d'descriptionValue'\x3e"+
g.replace(/(\r\n|\r|\n)/g,"\x3cbr/\x3e")+"\x3c/span\x3e\x3c/div\x3e");c.setContent(d+"\x3c/div\x3e\x3c/div\x3e");setTimeout(function(){u.focus(c.domNode)},1);c.openPopup()}}})});
//# sourceMappingURL=View.js.map