//>>built
require({cache:{"url:rdforms/apps/ValidatorTemplate.html":"\x3cdiv class\x3d'validator'\x3e\n  \x3cdiv data-dojo-type\x3d'dijit.TitlePane' title\x3d'RDF/JSON source' data-dojo-props\x3d\"open: ${rdfjsonEditorOpen}\"\x3e\n    \x3cdiv data-dojo-type\x3d'dijit.form.SimpleTextarea' data-dojo-attach-point\x3d'_rdfjsonDijit' style\x3d'width:100%;height:200px'\x3e\x3c/div\x3e\n    \x3cdiv data-dojo-type\x3d'dijit.form.Button' data-dojo-props\x3d\"label:'Update'\" dojoAttachEvent\x3d'onClick:_update'\x3e\x3c/div\x3e\n  \x3c/div\x3e\n  \x3cdiv class\x3d'json' data-dojo-attach-point\x3d'_jsonNode'\x3e\x3c/div\x3e\n  \x3cdiv class\x3d'rdfjson' data-dojo-attach-point\x3d'_rdfjsonNode'\x3e\x3c/div\x3e\n  \x3cdiv class\x3d'rforms' data-dojo-attach-point\x3d'_rformsNode'\x3e\x3c/div\x3e\n\x3c/div\x3e\n"}});
define("rdforms/apps/Validator","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/window dojo/json dojo/dom-class dojo/dom-construct dojo/dom-attr dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/TitlePane dijit/form/SimpleTextarea dijit/form/Button dijit/Dialog rdfjson/Graph ../model/Engine ../template/ItemStore ../view/ValidationPresenter dojo/text!./ValidatorTemplate.html".split(" "),function(n,l,k,p,m,e,a,f,q,r,s,t,A,B,C,u,v,w,x,y,z){return n([r,
s,t],{itemStore:null,type2template:null,rdfjson:null,rdfjsonEditorOpen:!1,templateString:z,postCreate:function(){this.inherited("postCreate",arguments);this.itemStore=this.itemStore||new x;"string"===typeof this.rdfjson?this._rdfjsonDijit.set("value",this.rdfjson):this._rdfjsonDijit.set("value",m.stringify(this.rdfjson,!0,"  "));this._update()},_update:function(){this._validateJSON();this._validateRDFJSON();this._validateRForms()},_validateJSON:function(){delete this._rdfjsonObj;try{this._rdfjsonObj=
m.parse(this._rdfjsonDijit.get("value")),e.toggle(this._jsonNode,"error",!1),f.set(this._jsonNode,"innerHTML","RDF input: Valid JSON")}catch(a){e.toggle(this._jsonNode,"error",!0),f.set(this._jsonNode,"innerHTML","RDF input: Invalid JSON: "+a)}},_validateRDFJSON:function(){delete this._graph;f.set(this._rdfjsonNode,"innerHTML","");e.toggle(this._rdfjsonNode,"error",!1);if(null!=this._rdfjsonObj)try{this._graph=new v(this._rdfjsonObj,!1),this._graph.validate(),a.create("div",{innerHTML:"RDF input: Valid RDF/JSON, "+
this._graph.report.nr+" statements found."},this._rdfjsonNode)}catch(b){e.toggle(this._rdfjsonNode,"error",!0),a.create("div",{innerHTML:"RDF input: Invalid RDF/JSON, although "+b.nr+" valid statements found."},this._rdfjsonNode),this._explainInvalidRDFJSON(b)}},_explainInvalidRDFJSON:function(b){var e=a.create("table",{"class":"report"},this._rdfjsonNode),d=a.create("tr",null,e);a.create("th",{innerHTML:"Subject"},d);a.create("th",{innerHTML:"Predicate"},d);a.create("th",{innerHTML:"ObjectNr"},d);
a.create("th",{innerHTML:"Error"},d);k.forEach(b.errors,function(b){var c=a.create("tr",null,e);a.create("td",{innerHTML:b.s},c);a.create("td",{innerHTML:b.p||""},c);a.create("td",{innerHTML:""+(b.oindex||"")},c);a.create("td",{innerHTML:b.message},c)})},_validateRForms:function(){f.set(this._rformsNode,"innerHTML","");e.toggle(this._rformsNode,"error",!1);if(null!=this._graph)for(var a in this.type2template)this.type2template.hasOwnProperty(a)&&this._checkInstances(a,this.type2template[a])},_checkInstances:function(b,
f){var d=this.itemStore.getTemplate(f),g=this._graph.find(null,"http://www.w3.org/TR/rdf-schema/type",b);0<g.length&&a.create("div",{"class":"instanceType",innerHTML:b},this._rformsNode);k.forEach(g,function(c){var b=a.create("div",{"class":"instance"},this._rformsNode),f=w.match(this._graph,c.getSubject(),d),h=f.report();if(0<h.errors.length||0<h.warnings.length){0<h.errors.length?e.add(b,"error"):e.add(b,"warning");a.create("div",{"class":"instanceHeading",innerHTML:"\x3cspan class\x3d'action info'\x3e\x3c/span\x3e\x26nbsp;\x3cb\x3e"+
c.getSubject()+"\x3c/b\x3e is not ok:",onclick:l.hitch(this,this._openView,f,d)},b);var g=a.create("table",{"class":"report"},b);c=a.create("tr",null,g);a.create("th",{innerHTML:"Severity"},c);a.create("th",{innerHTML:"Subject"},c);a.create("th",{innerHTML:"Predicate"},c);a.create("th",{innerHTML:"Problem"},c);k.forEach(h.errors,function(b){var c=a.create("tr",{"class":"error"},g);a.create("td",{innerHTML:"Error"},c);a.create("td",{innerHTML:b.parentBinding.getChildrenRootUri()},c);a.create("td",
{innerHTML:b.item.getProperty()},c);a.create("td",{innerHTML:b.message},c)});k.forEach(h.warnings,function(b){var c=a.create("tr",{"class":"warning"},g);a.create("td",{innerHTML:"Warning"},c);a.create("td",{innerHTML:b.parentBinding.getChildrenRootUri()},c);a.create("td",{innerHTML:b.item.getProperty()},c);a.create("td",{innerHTML:b.message},c)})}else a.create("div",{"class":"instanceHeading",innerHTML:"\x3cspan class\x3d'action info'\x3e\x3c/span\x3e\x26nbsp;\x3cb\x3e"+c.getSubject()+"\x3c/b\x3e is ok ",
onclick:l.hitch(this,this._openView,f,d)},b)},this)},_openView:function(b,e){var d=a.create("div"),f=new u({content:d}),d=new y({template:e,binding:b,includeLevel:"recommended",compact:!0},d),c=p.getBox();q.set(d.domNode,{width:Math.floor(0.7*c.w)+"px",height:Math.floor(0.7*c.h)+"px",overflow:"auto",position:"relative"});f.show()}})});
//# sourceMappingURL=Validator.js.map