//>>built
define("rdfjson/Graph",["./formats/rdfjson/util","./Statement","./namespaces"],function(k,p,l){var q=function(a){return 0===a.length?a:[a[0]]},m=function(a,b,c){return{object:function(g){for(var e=0;e<b.length;e++){var d;if(c)d=b[e].getSubject();else{d=b[e].getType();if("uri"===d||"bnode"===d)continue;d=b[e].getValue()}d=a.find(d,g);0<d.length&&m(a,[d[0]])}return m(a,[])},objects:function(g){var e=[],d;if(!0===c)for(d=0;d<b.length;d++)e=e.concat(a.find(b[d].getSubject(),g));else for(d=0;d<b.length;d++){var n=
b[d].getType();if("uri"===n||"bnode"===n)e=e.concat(a.find(b[d].getValue(),g))}return m(a,e)},constr:function(g,e){k.isString(e)&&(e={type:"uri",value:e});for(var d=[],n=0;n<b.length;n++){var f=c?b[n].getSubject():b[n].getValue();0<a.find(f,g,e).length&&d.push(b[n])}return m(a,d,c)},each:function(g,e){if(!0===c)for(var d=0;d<b.length;d++){var f="_:"===b[d].getSubject().substring(0,2)?"bnode":"uri";(null==e||e===f)&&g(m(a,b[d],c))}else for(d=0;d<b.length;d++)g(m(a,b[d],c))},nodes:function(a){var e=
[];if(!0===c)for(var d=0;d<b.length;d++){var f="_:"===b[d].getSubject().substring(0,2)?"bnode":"uri";(null==a||a===f)&&e.push({type:f,value:b[d].getSubject()})}else for(d=0;d<b.length;d++)(null==a||a===b[d].getType())&&e.push(b[d].getObject());return e},values:function(a){var e=[];if(!0===c)for(var d=0;d<b.length;d++){var f="_:"===b[d].getSubject().substring(0,2)?"bnode":"uri";(null==a||a===f)&&e.push(b[d].getSubject())}else for(d=0;d<b.length;d++)(null==a||a===b[d].getType())&&e.push(b[d].getValue());
return e},firstValue:function(a){if(!0===c)for(var e=0;e<b.length;e++){var d="_:"===b[e].getSubject().substring(0,2)?"bnode":"uri";if(null==a||a===d)return b[e].getSubject()}else for(e=0;e<b.length;e++)if(null==a||a===b[e].getType())return b[e].getValue()}}},f=function(a,b){this._graph=a||{};this._bnodes={};this._bnodesIndexed=!1;!1!==b&&this.validate();this._changed=!1};f.prototype.isEmpty=function(){var a,b,c,g=this._graph,e;for(a in g)if(g.hasOwnProperty(a))for(b in g[a])if(g[a].hasOwnProperty(b)){e=
g[a][b];for(c=e.length-1;0<=c;c--){var d=e[c];if(null==d._statement||d._statement.isAsserted())return!1}}return!0};f.prototype.onChange=function(){};f.prototype.setChanged=function(a){if(this._changed=!0===a||null==a?!0:!1)this.onChange()};f.prototype.isChanged=function(){return this._changed};f.prototype.addAll=function(a){var b={},c;a=a.find();for(var g=0;g<a.length;g++){c=a[g];var e=c.getSubject(),d=c.getPredicate(),f=c.getCleanObject();0===e.indexOf("_:")&&(c=b[e]||this._newBNode(),e=b[e]=c);
0===d.indexOf("_:")&&(c=b[d]||this._newBNode(),d=b[d]=c);"bnode"===f.type&&(c=b[f.value]||this._newBNode(),b[f.value]=c,f.value=c);this.add(e,d,f)}};f.prototype.add=function(a,b,c){return a instanceof p?(b=a.getPredicate(),c=a.getObject(),a=a.getSubject(),this._trackBNodes(a,b,c),c=this._graphObject(c),c=k.add(this._graph,a,b,c),this.setChanged(),this._get(a,b,c,!0)):this.create(a,b,c,!0)};f.prototype.addL=function(a,b,c,g){c={type:"literal",value:c};"string"===typeof g&&(c.lang=g);return this.create(a,
b,c,!0)};f.prototype.addD=function(a,b,c,g){c={type:"literal",value:c};"string"===typeof g&&(c.datatype=l.expand(g));return this.create(a,b,c,!0)};f.prototype.create=function(a,b,c,g){a=null==a?this._newBNode():l.expand(a);b=null==b?this._newBNode():l.expand(b);null==c?c={type:"bnode",value:this._newBNode()}:k.isString(c)?c={type:"uri",value:l.expand(c)}:(c={type:c.type,value:c.value,lang:c.lang,datatype:c.datatype},"uri"===c.type&&null!=c.value&&(c.value=l.expand(c.value)),c.datatype&&(c.datatype=
l.expand(c.datatype)));return!1!==g?(c=k.add(this._graph,a,b,c),this.setChanged(),this._getOrCreate(a,b,c,!0)):new p(this,a,b,c,!1)};f.prototype.findAndRemove=function(a,b,c){a=this.find(a,b,c);for(b=0;b<a.length;b++)this.remove(a[b])};f.prototype.remove=function(a){var b=a.getSubject(),c=a.getPredicate();a=a.getObject();this._trackBNodes(b,c,a);null!=k.remove(this._graph,b,c,a)&&this.setChanged()};f.prototype.find=function(a,b,c){"string"===typeof a&&(a=l.expand(a));"string"===typeof b&&(b=l.expand(b));
"object"===typeof c&&null!==c&&"uri"===c.type?c.value=l.expand(c.value):"string"===typeof c&&(c={type:"uri",value:l.expand(c)});if(null==c)return null==b?null==a?this._find():this._findS(a):null==a?this._findP(b):this._findSP(a,b);if(null==b)return null==a?this._findO(c):this._findSO(a,c);if(null==a)return this._findPO(b,c);a=this._get(a,b,k.contains(this._graph,a,b,c),!0);return null==a?[]:[a]};f.prototype.findFirstValue=function(a,b){var c=this.find(a,b);if(0<c.length)return c[0].getValue()};f.prototype.projection=
function(a,b,c){var g={},e,d;for(d in b)if(b.hasOwnProperty(d)){var f=this.find(a,b[d]);if(0<f.length){if("*"===d[0]){e=[];for(var h=0;h<f.length;h++)e[h]=f[h].getValue();g[d.substr(1)]=e}else g[d]=f[0].getValue();if(null!=c&&"none"!==c){switch(c){case "statement":e=f;break;case "objects":e=[];for(h=0;h<f.length;h++)e[h]=f[h].getCleanObject();break;case "values":e=[];for(h=0;h<f.length;h++)e[h]=f[h].getValue()}g["*"+d]=e}}}return g};f.prototype.subjects=function(a,b){return m(this,this.find(null,
a,b),!0)};f.prototype.subject=function(a,b){return m(this,q(this.find(null,a,b)),!0)};f.prototype.objects=function(a,b){return m(this,this.find(a,b,null))};f.prototype.object=function(a,b){return m(this,q(this.find(a,b,null)))};f.prototype.exportRDFJSON=function(){var a,b,c,g=this._graph,e={},d,f,h,k;for(a in g)if(g.hasOwnProperty(a))for(b in e[a]={},g[a])if(g[a].hasOwnProperty(b)){d=g[a][b];f=e[a][b]=[];for(c=d.length-1;0<=c;c--)h=d[c],k={type:h.type,value:h.value},null!=h.lang&&(k.lang=h.lang),
null!=h.datatype&&(k.datatype=h.datatype),f.push(k)}return e};f.prototype.replaceSubject=function(a,b){return this.replaceURI(a,b)};f.prototype.replaceURI=function(a,b){var c=this._graph;if(c.hasOwnProperty(a)){if(c.hasOwnProperty(b))throw"Cannot replace subject with target URI since it already exists.";c[b]=c[a];delete c[a];this._map(function(c,e,d){"uri"===d.type&&d.value===a&&(d.value=b);c===b&&d._statement&&(d._statement._s=b)})}return this};f.prototype.clone=function(){return new f(this.exportRDFJSON())};
f.prototype.findProperties=function(a){if(null==this._graph[a])return[];var b,c=this._graph,g=[];for(b in c[a])c[a].hasOwnProperty(b)&&g.push(b);return g};f.prototype.validate=function(){this.report=this._validate();if(!this.report.valid)throw this.report;return this.report};f.prototype.registerBNode=function(a){this._bnodes[a]=!0};f.prototype._get=function(a,b,c,g){if(null!=c)return this._getOrCreate(a,b,c,g)};f.prototype._getOrCreate=function(a,b,c,g){null==c._statement&&new p(this,a,b,c,g);return c._statement};
f.prototype._graphObject=function(a){return null==a._statement||a._statement._graph===this?a:{type:a.type,value:a.value,lang:a.lang,datatype:a.datatype}};f.prototype._findSP=function(a,b){if(null==this._graph[a]||null==this._graph[a][b])return[];for(var c=[],g=this._graph[a][b],e=0;e<g.length;e++)c[e]=this._get(a,b,g[e],!0);return c};f.prototype._findS=function(a){if(null==this._graph[a])return[];var b,c=this._graph,g=[];for(b in c[a])c[a].hasOwnProperty(b)&&g.push(this._findSP(a,b));return Array.prototype.concat.apply([],
g)};f.prototype._find=function(){var a=[],b=this;this._map(function(c,g,e){a.push(b._get(c,g,e,!0))});return a};f.prototype._findP=function(a){var b=[],c=this;this._map(function(g,e,d){a===e&&b.push(c._get(g,e,d,!0))});return b};f.prototype._findO=function(a){var b=[],c=this;this._map(function(g,e,d){k.objectEquals(a,d)&&b.push(c._get(g,e,d,!0))});return b};f.prototype._findSO=function(a,b){var c=[],g=this;this._map(function(e,d,f){a===e&&k.objectEquals(b,f)&&c.push(g._get(e,d,f,!0))});return c};
f.prototype._findPO=function(a,b){var c=[],g=this;this._map(function(e,d,f){a===d&&k.objectEquals(b,f)&&c.push(g._get(e,d,f,!0))});return c};f.prototype._map=function(a){var b,c,g,e=this._graph,d;for(b in e)if(e.hasOwnProperty(b))for(c in e[b])if(e[b].hasOwnProperty(c)){d=e[b][c];for(g=d.length-1;0<=g;g--)a(b,c,d[g])}};f.prototype._validate=function(){var a,b,c,g=this._graph,e,d={valid:!0,errors:[],nr:0};for(a in g)if(g.hasOwnProperty(a))if(k.isObject(g[a]))for(b in g[a]){if(g[a].hasOwnProperty(b))if(e=
g[a][b],k.isArray(e))for(c=e.length-1;0<=c;c--){var f=e[c];k.isObject(f)?null==f.type?(d.errors.push({s:a,p:b,oindex:c+1,message:"Object "+(c+1)+" in object array lacks the attribute type, must be either 'literal', 'resource' or 'bnode'."}),d.valid=!1):k.isString(f.value)?d.nr++:(d.errors.push({s:a,p:b,oindex:c+1,message:"Object "+(c+1)+" in object array must have the 'value' attribute pointing to a string."}),d.valid=!1):(d.errors.push({s:a,p:b,oindex:c+1,message:"Element "+(c+1)+" in object array is not an object."}),
d.valid=!1)}else d.errors.push({s:a,p:b,message:"Predicate must point to an array of objects."}),d.valid=!1}else d.errors.push({s:a,message:"Subject must point to an object."}),d.valid=!1;return d};f.prototype._newBNode=function(){this._indexBNodes();var a,b,c;for(a=1;10>a;a++)for(b=1;b<=a;b++)if(c="_:"+Math.floor(Math.random()*(Math.pow(10,a)+1)),!0!==this._bnodes[c])return this._bnodes[c]=!0,c};f.prototype._indexBNodes=function(){if(!this._bnodesIndexed){var a,b,c,f=this._graph,e;for(a in f)if(f.hasOwnProperty(a))for(b in 0===
a.indexOf("_:")&&(this._bnodes[a]=!0),f[a])if(f[a].hasOwnProperty(b)){0===b.indexOf("_:")&&(this._bnodes[b]=!0);e=f[a][b];for(c=e.length-1;0<=c;c--)"bnode"===e[c].type&&(this._bnodes[e[c].value]=!0)}this._bnodesIndexed=!0}};f.prototype._trackBNodes=function(a,b,c){0===a.indexOf("_:")&&(this._bnodes[a]=!0);0===b.indexOf("_:")&&(this._bnodes[b]=!0);"bnode"===c.type&&(this._bnodes[c.value]=!0)};return f});
//# sourceMappingURL=Graph.js.map