//>>built
define("rdfjson/Rdfs",["./Graph"],function(p){var b={rdf:"http://www.w3.org/1999/02/22-rdf-syntax-ns#",rdfs:"http://www.w3.org/2000/01/rdf-schema#",owl:"http://www.w3.org/2002/07/owl#"},h={rdftype:b.rdf+"type",rdfssco:b.rdfs+"subClassOf",rdfsdomain:b.rdfs+"domain",rdfsrange:b.rdfs+"range",rdfsspo:b.rdfs+"subPropertyOf",rdfsClass:b.rdfs+"Class",owlClass:b.owl+"Class",owlObjectProperty:b.owl+"ObjectProperty",owlDatatypeProperty:b.owl+"DatatypeProperty",rdfProperty:b.rdf+"Property"},m=function(a,c,l){var d=
{},e=!1;a=a.find(c,l);for(c=0;c<a.length;c++)l=a[c],"literal"===l.getType()&&(d[l.getLanguage()||""]=l.getValue()||"",e=!0);if(e)return null==d.en&&null!=d[""]&&(d.en=d[""],delete d[""]),d},n=function(a){for(var c=[],l={},d=0;d<a.length;d++){var e=a[d];l[e]||(c.push(e),l[e]=!0)}return c},g=function(a,c){this._uri=a;this._parents=[];this._children=[];this._graph=c};g.prototype.getURI=function(){return this._uri};g.prototype.getLabel=function(){var a=this.getLabels();if(null!=a.en)return a.en;for(var c in a)if(a.hasOwnProperty(c))return a[c];
return""};g.prototype.getLabels=function(){null==this._labels&&(this._labels=m(this._graph,this._uri,b.rdfs+"label"),null==this._labels&&(this._labels={en:this._uri.substr(this._uri.lastIndexOf("/")+1)}));return this._labels};g.prototype.getComment=function(){var a=this.getComments();if(null!=a){if(null!=a.en)return a.en;for(var c in a)if(a.hasOwnProperty(c))return a[c]}return""};g.prototype.getComments=function(){null==this._comments&&(this._comments=m(this._graph,this._uri,b.rdfs+"comment"));return this._comments};
g.prototype.addParent=function(a){this._parents.push(a);a._children.push(this)};g.prototype.getDirectParents=function(){return this._parents};g.prototype.getParents=function(){if(this._parentLock)return[];this._parentLock=!0;if(null==this._allParents){this._allParents=[];for(var a=0;a<this._parents.length;a++)this._allParents=this._allParents.concat(this._parents[a].getParents()),this._allParents.push(this._parents[a])}delete this._parentLock;return this._allParents};g.prototype.getChildren=function(){if(this._childLock)return[];
this._childLock=!0;if(null==this._allChildren){this._allChildren=[];for(var a=0;a<this._children.length;a++)this._allChildren=this._allChildren.concat(this._children[a].getChildren()),this._allChildren.push(this._children[a])}delete this._childLock;return this._allChildren};g.prototype.setRange=function(a){null==this._range&&(this._range=[]);this._range.push(a)};g.prototype.setDomain=function(a){null==this._domain&&(this._domain=[]);this._domain.push(a);a.setDomainOf(this)};g.prototype.getRange=function(){if(null==
this._allRange){this._allRange=this._range||[];for(var a=0;a<this._parents.length;a++)this._allRange=this._allRange.concat(this._parents[a].getRange());this._allRange=n(this._allRange)}return this._allRange};g.prototype.getDomain=function(){if(null==this._allDomain){this._allDomain=this._domain||[];for(var a=0;a<this._parents.length;a++)this._allDomain=this._allDomain.concat(this._parents[a].getDomain());this._allDomain=n(this._allDomain)}return this._allDomain};g.prototype.setDomainOf=function(a){null==
this._domainOf&&(this._domainOf=[]);this._domainOf.push(a)};g.prototype.getDomainOf=function(){return this._domainOf};g.prototype.getAllDomainOf=function(){if(this._domainOfLock)return[];this._domainOfLock=!0;if(null==this._allDomainOf){var a=this._domainOf||[];this._allDomainOf=this._domainOf||[];for(var c=0;c<a.length;c++)this._allDomainOf=this._allDomainOf.concat(a[c].getChildren());for(a=0;a<this._parents.length;a++)this._allDomainOf=this._allDomainOf.concat(this._parents[a].getAllDomainOf())}delete this._domainOfLock;
return this._allDomainOf};var k=function(a,c,l,d){for(var e=0;e<l.length;e++){var h=l[e],f=h.getSubject(),b=a[f];b||(b=new g(f,h.getGraph()),a[f]=b,c.push(b));if(d){var f=h.getValue(),k=a[f];k||(k=new g(f,h.getGraph()),a[f]=k,c.push(k));b.addParent(k)}}},f=function(){this._cidx={};this._carr=[];this._pidx={};this._parr=[]};f.prototype.ns=b;f.prototype.terms=h;f.prototype.addGraph=function(a){k(this._cidx,this._carr,a.find(null,h.rdftype,h.rdfsClass));k(this._cidx,this._carr,a.find(null,h.rdftype,
h.owlClass));k(this._cidx,this._carr,a.find(null,h.rdfssco,null),!0);k(this._pidx,this._parr,a.find(null,h.rdftype,h.rdfProperty));k(this._pidx,this._parr,a.find(null,h.rdfsspo,null),!0);k(this._pidx,this._parr,a.find(null,h.rdftype,h.owlDatatypeProperty));k(this._pidx,this._parr,a.find(null,h.rdftype,h.owlObjectProperty));for(var c=this._pidx,f=this._cidx,d,e,b=a.find(null,h.rdfsdomain,null),g=0;g<b.length;g++)e=b[g],d=c[e.getSubject()],e=f[e.getValue()],null!=d&&null!=e&&d.setDomain(e);b=a.find(null,
h.rdfsrange,null);for(a=0;a<b.length;a++)e=b[a],d=c[e.getSubject()],e=e.getValue(),null!=d&&null!=e&&d.setRange(e)};f.prototype.addThing=function(){var a=this._cidx["http://www.w3.org/2002/07/owl#Thing"],c=!1;a||(a=new g("http://www.w3.org/2002/07/owl#Thing",new p),this._cidx["http://www.w3.org/2002/07/owl#Thing"]=a,this._carr.push(a),c=!0);for(var b=0;b<this._carr.length;b++){var d=this._carr[b];c&&d!=a?d.addParent(a):-1===d.getParents().indexOf(a)&&d!=a&&d.addParent(a)}};f.prototype.getClasses=
function(){return this._carr};f.prototype.getProperties=function(){return this._parr};f.prototype.isClass=function(a){return null!=this._cidx[a]};f.prototype.isProperty=function(a){return null!=this._pidx[a]};f.prototype.getClass=function(a){return this._cidx[a]};f.prototype.getProperty=function(a){return this._pidx[a]};f.prototype.getInstances=function(a){var c=[];a=[a].concat(a.getChildren());for(var b=0;b<a.length;b++)for(var d=a[b],d=d.getGraph.find(null,h.rdftype,d.getURI()),e=0;e<d.length;e++)c.push(d[e].getSubject());
return c};f.global=new f;return f});
//# sourceMappingURL=Rdfs.js.map