//>>built
define("rdforms/model/GroupBinding",["dojo/_base/declare","./Binding","./CardinalityTracker"],function(k,l,m){return k(l,{_oneValidChild:void 0,_validPredicate:!0,_childBindings:null,_constraints:null,_cachedChildBindings:null,_rootUri:null,oneChildValidityChanged:function(a){if(a!==this._oneValidChild){if(!a&&(delete this._oneValidChild,this.isValid()))return!1;this._oneValidChild=a;this._notifyValidityChange(a&&this._validPredicate);return this._validPredicate}},getChildrenRootUri:function(){if(this._statement)return this._statement.getValue();
if(void 0!==this._rootUri)return this._rootUri;if(void 0!==this._parent)return this._parent.getChildrenRootUri()},addChildBinding:function(a){this.addChildBindings([a])},addChildBindings:function(a){this._cachedChildBindings=null;if(dojo.isArray(a)&&0!==a.length)for(var b=a[0].getItem(),c=this._item.getChildren(),d=c.length;0<=d;d--)if(b===c[d]){var g=0<this._childBindings[d].length?this._childBindings[d][0].getCardinalityTracker():new m(b);this._childBindings[d]=this._childBindings[d].concat(a);
dojo.forEach(a,function(a){a.setParent(this);a.setCardinalityTracker(g);g.increment()},this);break}},removeChildBinding:function(a){this._cachedChildBindings=null;for(var b=this._item.getChildren(),c=b.length;0<=c;c--)if(a.getItem()===b[c]){this._childBindings[c].splice(dojo.indexOf(this._childBindings[c],a),1);delete a._parent;a.getCardinalityTracker().decrement();break}this.oneChildValidityChanged()},getChildBindingsFor:function(a){for(var b=this._item.getChildren(),c=b.length;0<=c;c--)if(a===b[c])return this._childBindings[c]},
getItemGroupedChildBindings:function(){return this._childBindings},getChildBindings:function(){if(null===this._cachedChildBindings)if(this._childBindings&&0<this._childBindings.length){var a=[];this._cachedChildBindings=a.concat.apply(a,this._childBindings)}else this._cachedChildBindings=[];return this._cachedChildBindings},setPredicate:function(a){var b=this._validPredicate;this._isValidValue(a)?(this._statement.setPredicate(a),this._validPredicate=!0,!0!==b&&!0===this._oneValidChild&&this._notifyValidityChange(!0)):
(this._validPredicate=!1,!1!==b&&!0===this._oneValidChild&&this._notifyValidityChange(!1));this.updateAssertions()},getPredicate:function(){return this._statement.getPredicate()},report:function(a){null==a&&(a={errors:[],warnings:[]});var b=this.getItem().getChildren(),c=function(a){for(var b=0,c=0;c<a.length;c++)a[c].isValid()&&b++;return b};dojo.forEach(this.getItemGroupedChildBindings(),function(d,g){var e=b[g];if(null!=e.getProperty()){var h=c(d),f=e.getCardinality();null!=f.min&&f.min>h?a.errors.push({parentBinding:this,
item:e,message:"Too few valid values"}):null!=f.pref&&f.pref>h&&a.warnings.push({parentBinding:this,item:e,message:"Too few valid values"});null!=f.max&&f.max<h&&a.errors.push({parentBinding:this,item:e,message:"Too many values"})}"group"===e.getType()&&dojo.forEach(d,function(b){b.report(a)})},this);return a},constructor:function(a){this._constraints=a.constraints||[];this._childBindings=dojo.map(this._item.getChildren(),function(a){return[]});this._rootUri=a.childrenRootUri;this._statement&&(this._validPredicate=
this._isValidValue(this._statement.getPredicate()))},remove:function(){this._oneValidChild=!1;this.setAncestorValid(!1);void 0!==this._parent&&this._parent.removeChildBinding(this);this.inherited("remove",arguments)},isValid:function(){void 0===this._oneValidChild&&(this._oneValidChild=this._forceOneValidChildCheck());return this._oneValidChild&&this._validPredicate},setAncestorValid:function(a){this._ancestorValid=a;this.updateAssertions();dojo.forEach(this._childBindings,function(b){dojo.forEach(b,
function(b){b.setAncestorValid(a&&this._oneValidChild&&this._validPredicate)},this)},this)},updateAssertions:function(){void 0===this._oneValidChild&&this.isValid();var a=this._ancestorValid&&this._oneValidChild&&this._validPredicate;void 0!==this._statement&&this._statement.setAsserted(a);dojo.forEach(this._constraints,function(b){b.setAsserted(a)});dojo.forEach(this.getChildBindings(),function(a){a.updateAssertions()})},_forceOneValidChildCheck:function(){return dojo.some(this._childBindings,function(a){return dojo.some(a,
function(a){return a.isValid()})})},_notifyValidityChange:function(a){if(!this._parent||!this._parent.oneChildValidityChanged(a))this.updateAssertions(),dojo.forEach(this._childBindings,function(b){dojo.forEach(b,function(b){b.setAncestorValid(a)})})}})});
//# sourceMappingURL=GroupBinding.js.map