//>>built
define("rdforms/formulator/ItemTreeModel",["dojo/_base/declare","../template/Group","../template/Bundle","../template/Item"],function(n,m,h,p){var q=function(a,b){var c=a.getId()||a.getProperty(),d=b.getId()||b.getProperty();return c>d?1:c<d?-1:0},r=function(a,b){if(a.isReadOnly()&&!b.isReadOnly())return 1;if(b.isReadOnly()&&!a.isReadOnly())return-1;var c=a.getPath()||a.getInternalId(),d=b.getPath()||b.getInternalId();return c>d?1:c<d?-1:0};return n(null,{constructor:function(a){this.itemStore=a},
getRoot:function(a){a(this.itemStore)},mayHaveChildren:function(a){return a instanceof m||a instanceof h||a===this.itemStore},getChildren:function(a,b,c){a instanceof m?b(a.getChildren(!0)):a instanceof h?b(a.getItems().sort(q)):a===this.itemStore?b(a.getBundles().sort(r)):b([])},showError:function(a,b){},getIdentity:function(a){return a instanceof h?a.getInternalId():a===this.itemStore?"___root":a._internalId},getLabel:function(a){return a instanceof h?a.getPath()||a.getInternalId():a===this.itemStore?
"Root node":a.getId(!0)||a.getLabel(!1,!0)||a.getId()||a.getLabel()||a.getProperty(!0)||a.getProperty()||"??? (missing label and/or property)."},newItem:function(a,b,c){var d,e;d=a.id?{id:a.id}:a.getSource(!0);if(b instanceof h)e=b.getItems(),(b.getSource().templates||b.getSource().auxilliary).push(d);else{if(b===this.itemStore)throw"Solve in calling method instead.";e=b.getChildren(!0);var g=b.getSource(!0);g.items=g.items||[];isNaN(c)?(g.items.push(d),e.push(a)):(g.items.splice(c,0,d),e.splice(c,
0,a))}this.onChildrenChange(b,e)},removeItem:function(a,b){if(b!==this.itemStore){var c,d;if(b instanceof h){c=b.getItems();d=b.getSource().templates||b.getSource().auxilliary;var e=c.indexOf(a);c.splice(e,1);e=d.indexOf(a.getSource(!0))}else c=b.getChildren(!0),d=b.getSource(!0).items,e=c.indexOf(a),c.splice(e,1);d.splice(e,1);this.onChildrenChange(b,c)}},isItem:function(a){return a===this.itemStore||a instanceof h||a instanceof p},getPasteAction:function(a,b,c){return b===this.itemStore||c===this.itemStore?
"NA_paste_item_in_or_from_itemStore":b instanceof h?b===c?"NA_bundle_reorder":c instanceof h?"NA_move_between_bundles":-1===c.getChildren().indexOf(a)?c.getBundle().isReadOnly()?"NA_readOnly_destination":"reference_item_in_group":"NA_item_already_referenced_in_group":c instanceof h?a.getBundle()===c?"NA_un_inline":"NA_cross_bundle_un_inline":c.getBundle().isReadOnly()?"NA_readOnly_destination":b===c?"reorder_in_group":b.getBundle()===c.getBundle()?"move_between_groups_in_same_bundle":b.getBundle().isReadOnly()?
"NA_move_from_readOnly_source":"move_between_groups_in_different_bundles"},pasteItem:function(a,b,c,d,e){var g=this.getPasteAction(a,b,c);if("N"!==g[0]){var k;d=c.getChildren(!0);var f=c.getSource(!0);f.items=f.items||[];f=f.items;switch(g){case "reference_item_in_group":e=isNaN(e)?d.length:e;d.splice(e,0,a);f.splice(e,0,{id:a.getId()});this.onChildrenChange(c,d);break;case "reorder_in_group":case "move_between_groups_in_same_bundle":case "move_between_groups_in_different_bundles":g=b.getChildren(!0);
k=b.getSource(!0).items;var h=g.indexOf(a),m=k[h];g.splice(h,1);k.splice(h,1);e=isNaN(e)?d.length:e;d.splice(e,0,a);f.splice(e,0,m);this.onChildrenChange(c,d);if(b!==c)this.onChildrenChange(b,g)}}},old_pasteItem:function(a,b,c,d,e){if(!(b===this.itemStore||c===this.itemStore)){var g,k;b instanceof h?(g=b.getItems(),k=b.getSource(),k=k.templates||k.auxilliary):(g=b.getChildren(!0),k=b.getSource(!0).items);if(k){var f=g.indexOf(a);d=null==a.getId()?k[f]:{id:a.getId()};g.splice(f,1);k.splice(f,1)}else d=
{id:a.getId()};if(b===c)isNaN(e)?(g.push(a),k.push(d)):(g.splice(e,0,a),k.splice(e,0,d)),this.onChildrenChange(b,g);else{var l;c instanceof h?(f=c.getSource(),null==f.templates&&null==f.auxilliary&&(f.templates=[]),f=f.templates||f.auxilliary,l=c.getItems()):(f=c.getSource(!0),f.items=f.items||[],f=f.items,l=c.getChildren(!0));isNaN(e)?(l.push(a),f.push(d)):(l.splice(e,0,a),f.splice(e,0,d));if(k)this.onChildrenChange(b,g);this.onChildrenChange(c,l)}}},onChange:function(a){},onChildrenChange:function(a,
b){a.originalChildrenChanged&&a.originalChildrenChanged()}})});
//# sourceMappingURL=ItemTreeModel.js.map