//>>built
define("rdfjson/formats/rdfxml/Rdfparser",["./uri"],function(k){var d;return d=function(l){d.ns={RDF:"http://www.w3.org/1999/02/22-rdf-syntax-ns#",RDFS:"http://www.w3.org/2000/01/rdf-schema#"};d.nodeType={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION:12};this.frameFactory=function(a,e,f){return{NODE:1,ARC:2,parent:e,parser:a,store:a.store,element:f,lastChild:0,base:null,lang:null,
node:null,nodeType:null,listIndex:1,rdfid:null,datatype:null,collection:!1,terminateFrame:function(){this.collection&&this.node.close()},addSymbol:function(a,b){b=k.join(b,this.base);this.node=this.store.sym(b);this.nodeType=a},loadTriple:function(){this.parent.parent.collection?this.parent.parent.node.append(this.node):this.store.add(this.parent.parent.node,this.parent.node,this.node,this.parser.why);if(null!=this.parent.rdfid){var a=this.store.sym(k.join("#"+this.parent.rdfid,this.base));this.store.add(a,
this.store.sym(d.ns.RDF+"type"),this.store.sym(d.ns.RDF+"Statement"),this.parser.why);this.store.add(a,this.store.sym(d.ns.RDF+"subject"),this.parent.parent.node,this.parser.why);this.store.add(a,this.store.sym(d.ns.RDF+"predicate"),this.parent.node,this.parser.why);this.store.add(a,this.store.sym(d.ns.RDF+"object"),this.node,this.parser.why)}},isTripleToLoad:function(){return null!=this.parent&&null!=this.parent.parent&&this.nodeType==this.NODE&&this.parent.nodeType==this.ARC&&this.parent.parent.nodeType==
this.NODE},addNode:function(a){this.addSymbol(this.NODE,a);this.isTripleToLoad()&&this.loadTriple()},addCollection:function(){this.nodeType=this.NODE;this.node=this.store.collection();this.collection=!0;this.isTripleToLoad()&&this.loadTriple()},addCollectionArc:function(){this.nodeType=this.ARC},addBNode:function(a){this.node=null!=a?null!=this.parser.bnodes[a]?this.parser.bnodes[a]:this.parser.bnodes[a]=this.store.bnode():this.store.bnode();this.nodeType=this.NODE;this.isTripleToLoad()&&this.loadTriple()},
addArc:function(a){a==d.ns.RDF+"li"&&(a=d.ns.RDF+"_"+this.parent.listIndex++);this.addSymbol(this.ARC,a)},addLiteral:function(a){this.node=this.parent.datatype?this.store.literal(a,"",this.store.sym(this.parent.datatype)):this.store.literal(a,this.lang);this.nodeType=this.NODE;this.isTripleToLoad()&&this.loadTriple()}}};this.store=l;this.bnodes={};this.why=null;this.reify=!1;this.parse=function(a,e,f){var c=a.childNodes,b;this.cleanParser();if(a.nodeType==d.nodeType.DOCUMENT)for(a=0;a<c.length;a++){if(c[a].nodeType==
d.nodeType.ELEMENT){b=c[a];break}}else if(a.nodeType==d.nodeType.ELEMENT)b=a;else throw Error("RDFParser: can't find root in "+e+". Halting. ");this.why=f;f=this.frameFactory(this);f.base=e;f.lang="";this.parseDOM(this.buildFrame(f,b));return!0};this.parseDOM=function(a){for(var e=function(a){return a.namespaceURI+a.localName},f=!0;a.parent;){var c,b=a.element,h=b.attributes;if(b.nodeType==d.nodeType.TEXT||b.nodeType==d.nodeType.CDATA_SECTION)a.addLiteral(b.nodeValue);else if(e(b)!=d.ns.RDF+"RDF")if(a.parent&&
a.parent.collection&&(a.addCollectionArc(),a=this.buildFrame(a,a.element),a.parent.element=null),!a.parent||!a.parent.nodeType||a.parent.nodeType==a.ARC){var g=b.getAttributeNodeNS(d.ns.RDF,"about");c=b.getAttributeNodeNS(d.ns.RDF,"ID");if(g&&c)throw Error("RDFParser: "+b.nodeName+" has both rdf:id and rdf:about. Halting. Only one of these properties may be specified on a node.");null==g&&c?(a.addNode("#"+c.nodeValue),b.removeAttributeNode(c)):null==g&&null==c?(c=b.getAttributeNodeNS(d.ns.RDF,"nodeID"))?
(a.addBNode(c.nodeValue),b.removeAttributeNode(c)):a.addBNode():(a.addNode(g.nodeValue),b.removeAttributeNode(g));c=b.getAttributeNodeNS(d.ns.RDF,"type");d.ns.RDF+"Description"!=e(b)&&(c={nodeValue:e(b)});null!=c&&(this.store.add(a.node,this.store.sym(d.ns.RDF+"type"),this.store.sym(k.join(c.nodeValue,a.base)),this.why),c.nodeName&&b.removeAttributeNode(c));for(b=h.length-1;0<=b;b--)this.store.add(a.node,this.store.sym(e(h[b])),this.store.literal(h[b].nodeValue,a.lang),this.why)}else{a.addArc(e(b));
if(this.reify&&(c=b.getAttributeNodeNS(d.ns.RDF,"ID")))a.rdfid=c.nodeValue,b.removeAttributeNode(c);c=b.getAttributeNodeNS(d.ns.RDF,"parseType");if(g=b.getAttributeNodeNS(d.ns.RDF,"datatype"))a.datatype=g.nodeValue,b.removeAttributeNode(g);c&&(g=c.nodeValue,"Literal"==g?(a.datatype=d.ns.RDF+"XMLLiteral",a=this.buildFrame(a),a.addLiteral(b),f=!1):"Resource"==g?(a=this.buildFrame(a,a.element),a.parent.element=null,a.addBNode()):"Collection"==g&&(a=this.buildFrame(a,a.element),a.parent.element=null,
a.addCollection()),b.removeAttributeNode(c));if(0!=h.length){g=b.getAttributeNodeNS(d.ns.RDF,"resource");c=b.getAttributeNodeNS(d.ns.RDF,"nodeID");a=this.buildFrame(a);g?(a.addNode(g.nodeValue),b.removeAttributeNode(g)):c?(a.addBNode(c.nodeValue),b.removeAttributeNode(c)):a.addBNode();for(b=h.length-1;0<=b;b--)c=this.buildFrame(a),c.addArc(e(h[b])),e(h[b])==d.ns.RDF+"type"?this.buildFrame(c).addNode(h[b].nodeValue):this.buildFrame(c).addLiteral(h[b].nodeValue)}else 0==b.childNodes.length&&this.buildFrame(a).addLiteral("")}for(b=
a.element;a.parent;){for(h=a;null==b;)a=a.parent,b=a.element;c=b.childNodes;c=null!=c?c[a.lastChild]:null;if(null==c||!f){a.terminateFrame();if(!(a=a.parent))break;b=a.element;f=!0}else if(c.nodeType!=d.nodeType.ELEMENT&&c.nodeType!=d.nodeType.TEXT&&c.nodeType!=d.nodeType.CDATA_SECTION||(c.nodeType==d.nodeType.TEXT||c.nodeType==d.nodeType.CDATA_SECTION)&&1!=b.childNodes.length)a.lastChild++;else{a.lastChild++;a=this.buildFrame(h,b.childNodes[a.lastChild-1]);break}}}};this.cleanParser=function(){this.bnodes=
{};this.why=null};this.buildFrame=function(a,e){var f=this.frameFactory(this,a,e);a&&(f.base=a.base,f.lang=a.lang);if(null==e||e.nodeType==d.nodeType.TEXT||e.nodeType==d.nodeType.CDATA_SECTION)return f;var c=e.attributes,b=e.getAttributeNode("xml:base");null!=b&&(f.base=b.nodeValue,e.removeAttribute("xml:base"));b=e.getAttributeNode("xml:lang");null!=b&&(f.lang=b.nodeValue,e.removeAttribute("xml:lang"));for(b=c.length-1;0<=b;b--)"xml"==c[b].nodeName.substr(0,3)&&e.removeAttributeNode(c[b]);return f}}});
//# sourceMappingURL=Rdfparser.js.map